changelog:
  - 1.4.6 (2024-11-04):
      - Analytics updates (ccv, views, ...)
  - 1.4.5 (2024-10-21):
      - Add summary feature
  - 1.4.4 (2024-10-08):
    - Add transcript feature
  - 1.4.3 (2024-09-30):
    - Add /tags API endpoint
  - 1.4.2 (2024-09-16):
    - Add discarded video endpoints
  - 1.4.1 (2024-09-05):
    - Add sort parameters in analytics endpoints
  - 1.4.0 (2024-07-29):
    - Add new analytics methods
    - Add livestream complete() method
  - 1.3.3 (2024-04-25):
    - Add API to get rate limiting headers
  - 1.3.2 (2024-02-19):
    - Update VideoStatusIngest enum
  - 1.3.1 (2023-08-10):
    - Fix upload with upload token and video id when video is smaller than chunk size
  - 1.3.0 (2023-06-28):
    - Introducing new live streams restream feature
    - Introducing new analytics endpoints
  - 1.2.7 (2022-09-13):
    - period parameter is now mandatory in analytics endpoints
  - 1.2.6 (2022-07-05):
    - Add SDK origin header
  - 1.2.5 (2022-04-21):
    - Fix `video.publishedAt` type
  - 1.2.4 (2022-03-21):
    - Add `ingest.receivedParts` attribute in GET /videos/{video_id}/status
  - 1.2.3 (2022-03-17):
    - Fix metadata query param in GET /videos
  - 1.2.2 (2022-03-10):
    - Add Origin identification headers
  - 1.2.1 (2022-01-24):
    - Add applicationName parameter (to allow user agent extension)
  - 1.2.0 (2022-01-07):
    - Add watermark endpoints
    - Add video clips
    - Fix tags[] query parameter format of GET /videos
    - Correctly distinguish between "undefined", "defined" and "null" values if the playerId parameter of PATCH /videos/{videoId}
  - 1.1.1 (2021-12-13):
    - Add an interface for progressive upload session
  - 1.1.0 (2021-12-06):
    - Add `name attribute in player themes
  - 0.0.11 (2021-11-15):
    - Add support of `progressive uploads`

originClient: java
invokerPackage: video.api.client.api
apiPackage: video.api.client.api.clients
modelPackage: video.api.client.api.models
groupId: video.api
artifactDescription: api.video Java API client
artifactUrl: https://github.com/apivideo/api.video-java-client
scmConnection: scm:git:git://github.com/apivideo/api.video-java-client.git
scmDeveloperConnection: scm:git:ssh://github.com:apivideo/api.video-java-client.git
gitRepoId: api.video-java-client
scmUrl: https://github.com/apivideo/api.video-java-client
developerName: api.video ecosystem team
developerOrganization: api.video
developerOrganizationUrl: https://api.video
developerEmail: ecosystem@api.video
licenseName: MIT License
licenseUrl: http://www.opensource.org/licenses/mit-license.php
library: okhttp-gson
dateLibrary: java8
sourceFolder: src/main/java
artifactId: java-api-client
hideGenerationTimestamp: true
serializableModel: "true"
java8: "true"
client: "true"
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  Nullable.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Nullable.java
  DeepObject.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: DeepObject.java
  Environment.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Environment.java
  page.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Page.java
  ApiVideoAuthInterceptor.mustache:
    folder: src/main/java/video/api/client/api/auth
    destinationFilename: ApiVideoAuthInterceptor.java
  EmptyArrayFixTypeAdapterFactory.mustache:
    folder: src/main/java/video/api/client/api
    destinationFilename: EmptyArrayFixTypeAdapterFactory.java
  IProgressiveUploadSession.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: IProgressiveUploadSession.java
  UploadChunkRequestBody.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadChunkRequestBody.java
  UploadProgressListener.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadProgressListener.java
  UploadPartProgressListener.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadPartProgressListener.java
  ApiVideoClient.mustache:
    folder: src/main/java/video/api/client
    destinationFilename: ApiVideoClient.java
  pagination.md.mustache:
    folder: docs
    destinationFilename: Pagination.md
  post-generate-java.sh:
    destinationFilename: post-generate.sh
