changelog:
  - 1.2.2 (2022-03-10):
      - Add Origin identification headers
  - 1.2.1 (2022-01-24):
      - Add applicationName parameter (to allow user agent extension)
  - 1.2.0 (2022-01-07):
      - Add watermark endpoints
      - Add video clips
      - Fix tags[] query parameter format of GET /videos
      - Correctly distinguish between "undefined", "defined" and "null" values if the playerId parameter of PATCH /videos/{videoId}
  - 1.1.1 (2021-12-13):
      - Add an interface for progressive upload session
  - 1.1.0 (2021-12-06):
      - Add `name attribute in player themes
  - 0.0.11 (2021-11-15):
      - Add support of `progressive uploads`

originClient: java
invokerPackage: video.api.client.api
apiPackage: video.api.client.api.clients
modelPackage: video.api.client.api.models
groupId: video.api
artifactDescription: api.video Java API client
artifactUrl: https://github.com/apivideo/api.video-java-client
scmConnection: scm:git:git://github.com/apivideo/api.video-java-client.git
scmDeveloperConnection: scm:git:ssh://github.com:apivideo/api.video-java-client.git
gitRepoId: api.video-java-client
scmUrl: https://github.com/apivideo/api.video-java-client
developerName: api.video ecosystem team
developerOrganization: api.video
developerOrganizationUrl: https://api.video
developerEmail: ecosystem@api.video
licenseName: MIT License
licenseUrl: http://www.opensource.org/licenses/mit-license.php
library: okhttp-gson
dateLibrary: java8
sourceFolder: src/main/java
artifactId: java-api-client
hideGenerationTimestamp: true
serializableModel: "true"
java8: "true"
client: "true"
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024

files:
  Nullable.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Nullable.java
  Environment.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Environment.java
  page.mustache:
    folder: src/main/java/video/api/client/api/models
    destinationFilename: Page.java
  ApiVideoAuthInterceptor.mustache:
    folder: src/main/java/video/api/client/api/auth
    destinationFilename: ApiVideoAuthInterceptor.java
  EmptyArrayFixTypeAdapterFactory.mustache:
    folder: src/main/java/video/api/client/api
    destinationFilename: EmptyArrayFixTypeAdapterFactory.java
  IProgressiveUploadSession.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: IProgressiveUploadSession.java
  UploadChunkRequestBody.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadChunkRequestBody.java
  UploadProgressListener.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadProgressListener.java
  UploadPartProgressListener.mustache:
    folder: src/main/java/video/api/client/api/upload
    destinationFilename: UploadPartProgressListener.java
  ApiVideoClient.mustache:
    folder: src/main/java/video/api/client
    destinationFilename: ApiVideoClient.java
  pagination.md.mustache:
    folder: docs
    destinationFilename: Pagination.md
  post-generate-java.sh:
    destinationFilename: post-generate.sh
