packageVersion: 1.1.0
licenseInfo: MIT
packageName: apivideo
projectName: api.video
appShortDescription: api.video Python API client
infoName: api.video ecosystem team
infoEmail: ecosystem@api.video
packageUrl: https://github.com/apivideo/api.video-python-client
gitRepoId: api.video-python-client
ignoredFiles:
  - gitlab-ci.mustache
  - travis.mustache
  - git_push.sh.mustache
  - model_test.mustache
defaultChunkSize: 50 * 1024 * 1024
minChunkSize: 5 * 1024 * 1024
maxChunkSize: 128 * 1024 * 1024
files:
  post-generate.sh:
    destinationFilename: post-generate.sh